services:
  - type: web
    name: job-crawler-api
    env: python
    region: oregon
    plan: free
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT src.api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
